### ISSUE TITLE
file_get_contents can be blocked on some servers...

### ISSUE THREAD

**Issue by dingo-d** [infinum/wp-boilerplate#106]
https://github.com/infinum/wp-boilerplate/blob/4706f9b6590cd819ff948b1d00932c1ebb86b7a4/wp-content/themes/inf_theme/includes/class-main.php#L201

For `file_get_contents()` to work [allow-url-fopen](http://php.net/manual/en/filesystem.configuration.php#ini.allow-url-fopen) has to be enabled on the server. 

We should use `wp_remote_get()` or `wp_remote_request()` for this.

Why did we switch from it?

**Comment by iruzevic** [comment]
because wp_remote_get has problems accessing the URL when the site is behind VPN or htaccess. Also, there has been some problems with https

**Comment by dingo-d** [comment]
> we agreed that file_get_contents will be safer option

Yeah, we agreed, but since then I had some complaints on my plugins that certain features didn't work, and in some personal projects I did the same thing happened because the hosting company usually disables `allow-url-fopen`, which will cause issues with `file_get_contents()`.

`wp_remote_get()` should be superior, as it handles tons of cases (check the request method of [WP_HTTP](https://developer.wordpress.org/reference/classes/wp_http/) class).

We can go through possible issues you mentioned, and find some kind of workaround (a `try/catch` to see if one method works or not, and use another instead).

**Comment by iruzevic** [comment]
replaced with file
