### ISSUE TITLE
Bugsnag plugin to webpack

### ISSUE THREAD

**Issue by iruzevic** [infinum/wp-boilerplate#108]
I found this as I see We can add bugsnag config directly in webpack.config.js

https://docs.bugsnag.com/build-integrations/webpack/#uploading-source-maps

@dingo-d what do you think?

**Comment by dingo-d** [comment]
We should add this in the branch that we use for work purposes, and make a wiki entry about adding it if the user wants to.

I wouldn't bundle bugsnag in the base boilerplate, as the free option is somewhat limited, plus people may use other things to monitor errors on the JS side of the theme 🙂.

But for the work related stuff, I'd definitely like to explore the option in the link via webpack :+1:
