### ISSUE TITLE
Try to setup a zero config setup

### ISSUE THREAD

**Issue by dingo-d** [infinum/wp-boilerplate#114]
I was testing the [create-guten-block](https://github.com/ahmadawais/create-guten-block) and I was blown away by how good it looks when you run it (even running `npm start` looks really cool).

I would love if we could have the same functionality. 

The flow would be something along these lines

Run `npx setup-theme` which will then automatically run the `npm install`, `composer install` and the rename script. 
Also, we should see the best way to make it portable. It can be cumbersome for new developers to keep track of the vendor files etc. Placing everything in a `src` folder which would have all the necessary things for a copy/paste theme from local to a server using FTP would also be a plus.

We could also publish the boilerplate on composer or npm (or maybe both?). The ease of use would bring a lot of exposure to the project I believe (we can write an article about it etc.).

Would love to have this in the 3.0.0 version :) 

Thoughts @infinum/eightshift-team?

**Comment by IvanGrginovInf** [comment]
Love the idea of it being a 1 line, no hassle setup. (tho you'd still have to rename things, maybe the basic setup would skip that part? (i.e. we give it a reasonable defaults, if you wish to rename things like it is now you'd have an "advanced" setup by running `npx setup-theme-advanced`)

Ideally it would be on npm so you could just run `npm install infinum-wp-boilerplate` (there doesn't seem to be any obstacles to [publishing on npm](https://docs.npmjs.com/getting-started/publishing-npm-packages).

Maybe we should all sit, write down all the things that need to be done and spread the work?

**Comment by dingo-d** [comment]
Related PR: #115

**Comment by iruzevic** [comment]
this is tested and it will go out in version 3
