### ISSUE TITLE
Add changelog.md

### ISSUE THREAD

**Issue by dingo-d** [infinum/wp-boilerplate#123]
It would be good to try to create a changelog kinda like this one: [WPCS Changelog](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/blob/develop/CHANGELOG.md)

Release notes can be used as a starting point, but a more detailed changelog would be great to have.

**Comment by IvanGrginovInf** [comment]
Sounds great, we can adopt their way quite easily.

Release naming
---
- `version` - `date` (example: _1.0.0 - 01.01.2019_)

Release content
---

- Notes (if needed)
- Types of changes: `Added`, `Changed`, `Deprecated `, `Removed`, `Fixed`

**Comment by dingo-d** [comment]
Added to the #133 PR
