### ISSUE TITLE
How to add shortcodes?

### ISSUE THREAD

**Issue by miloandco** [infinum/wp-boilerplate#139]
Hello, could you please provide an example on how to add custom shortcodes?

**Comment by gabriel-glo** [comment]
What you would want to do is create a new class for shortcodes with appropriate namespace. I would suggest that you do this inside the `admin` directory 
In that class define a method that will call `add_shortcode()` function with 2 arguments: shortcode name and shortcode callback method.
Define a new shortcode callback method which will hold the output of the shortcode.
You can define multiple shortcodes this way.

Now all you need to do is add action hook for registering the shortcodes (method that calls `add_shortcode()` function).
In `includes/class-main.php` include this newly created class with its namespace and instantiate a new object of that class. 
You can hook shortcode registering method on `init` action.

I hope the general workflow is more clearer. Feel free to shoot us more questions if it's needed.

**Comment by iruzevic** [comment]
as my colleague said creat new class called class-shortcodes.php in the admin folder.

**admin/class-shortcodes.php**
```
namespace Inf_Theme\Admin;

use Inf_Theme\Plugins\Acf;

/**
 * Class Shortcodes
 */
class Shortcodes {

  /**
   * Register shortcode function
   *
   * @since 2.0.0
   */
  public function register_shortcode() {
    add_shortcode( 'general-icon', array( $this, 'shortcode_icon' ) );
  }


  /**
   * Return shortcode icon
   *
   * @param string $attr Attribute to pass to shortcode.
   * @return string;
   *
   * @since 2.0.0
   */
  public function shortcode_icon( $attr ) {
    $args = shortcode_atts(
      array(
        'class' => '',
      ),
      $attr
    );

    return '<i class="icon--' . ( $args['class'] ) . '"></i>';
  }
}
```

**includes/class-main.php**
```
  /**
   * Register all of the hooks related to the admin area functionality.
   *
   * @since 2.0.0
   */
  private function define_admin_hooks() {

    $shortcodes    = new Admin\Shortcodes();

    // Shortcodes.
    $this->loader->add_action( 'init', $shortcodes, 'register_shortcode' );

  }
```

this is an example for the version 3 boilerplate

**Comment by miloandco** [comment]
Thanks, works like a charm :)
