### ISSUE TITLE
Problem npx create-wp-theme

### ISSUE THREAD

**Issue by PatriceBois** [infinum/wp-boilerplate#149]
Can't seem to make it work...

I have this error : 
- Error: Command failed: cd "/Users/patricebois/Desktop/WWW/provalis/wp-content/themes/provalis" && npm run build
npm ERR! code ELIFECYCLE                                                                         
npm ERR! errno 2
npm ERR! provalis@4.0.0 build: `webpack --progress --mode production`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the provalis@4.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/patricebois/.npm/_logs/2019-06-26T00_55_15_693Z-debug.log
![Capture d’écran 2019-06-25 à 21 04 33](https://user-images.githubusercontent.com/4474398/60143613-e681e980-978c-11e9-9b2b-6dcdeacd881c.png)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* PHP version:
* Development environment: 
* Server type: 
* Operating System and version:

**Comment by dingo-d** [comment]
Hi! Can you fill in the environment part so that we can try ro reproduce the bug easily? Thanks 🙂

**Comment by IvanGrginovInf** [comment]
Hi @PatriceBois, are you sure the folder was empty before you started? I'm unable to reliably reproduce this issue (works fine for me) but I've had this happen once during testing when I've been installing and deleting node_modules multiple times in a single folder.

Can you please try these steps:
1. Go to your new theme's folder (based on your screenshot that would be `wp-contet/themes/provalis`
2. Delete the `node_modules` folder
3. Run `npm install`
4. Run `npm run build`

**Comment by PatriceBois** [comment]
@dingo-d : I'm on my MacBook Air, with High Sierra

@IvanGrginovInf : I deleted multiple time my theme folder so node_modules was deleted each time...

**Comment by IvanGrginovInf** [comment]
@PatriceBois could you please provide the contents of the debug log?
`/Users/patricebois/.npm/_logs/2019-06-26T00_55_15_693Z-debug.log`

**Comment by PatriceBois** [comment]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@6.3.0
3 info using node@v8.1.2
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle provalis@4.0.0~prebuild: provalis@4.0.0
6 info lifecycle provalis@4.0.0~build: provalis@4.0.0
7 verbose lifecycle provalis@4.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle provalis@4.0.0~build: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/patricebois/Desktop/WWW/provalis/wp-content/themes/provalis/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle provalis@4.0.0~build: CWD: /Users/patricebois/Desktop/WWW/provalis/wp-content/themes/provalis
10 silly lifecycle provalis@4.0.0~build: Args: [ '-c', 'webpack --progress --mode production' ]
11 silly lifecycle provalis@4.0.0~build: Returned: code: 2  signal: null
12 info lifecycle provalis@4.0.0~build: Failed to exec build script
13 verbose stack Error: provalis@4.0.0 build: `webpack --progress --mode production`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:897:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
14 verbose pkgid provalis@4.0.0
15 verbose cwd /Users/patricebois/Desktop/WWW/provalis/wp-content/themes/provalis
16 verbose Darwin 17.5.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
18 verbose node v8.1.2
19 verbose npm  v6.3.0
20 error code ELIFECYCLE
21 error errno 2
22 error provalis@4.0.0 build: `webpack --progress --mode production`
22 error Exit status 2
23 error Failed at the provalis@4.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]

**Comment by dingo-d** [comment]
Hi, can you run these commands in your terminal and paste the results here, so that we have more information? 🙂 

**PHP version**: `php -v` (should be something like PHP 7.2.14 or something like that)
**Development environment**: (if you are using docker, vvv, mamp, homestead, locally set up or something else)
**Server type**: (apache, nginx, litespeed)
**Operating System and version**: (MacOS HighSierra 10.14.5 (18F132) or something like this)
**Node version**: `node -v`
**NPM version**: `npm -v`
**Composer version**: `composer -V`

**Comment by IvanGrginovInf** [comment]
```
...
3 info using node@v8.1.2
...
```

@PatriceBois I've tested it using your node version `8.1.2` and it seems it is causing the issue.

Please upgrade your node version to one of the following:
-  LTS Carbon version (`8.16.0`) (if you really need the 8.x.x version),
- LTS Dubnium  version (`10.16.0`)
- To the latest ( `12.4.0` at the time of writing this )

You can use [NVM](https://github.com/nvm-sh/nvm) to upgrade your node version.

**Comment by PatriceBois** [comment]
Nice it's working... with the node update! ;) Thanks guys

**Comment by IvanGrginovInf** [comment]
@PatriceBois glad that it's working! Will add the minimum node requirements to the README. Closing issue.
