### ISSUE TITLE
Syntax check

### ISSUE THREAD

**Issue by szepeviktor** [infinum/wp-boilerplate#160]
I work for developer teams and talk them into using 3 tests.

- syntax check (dumbest)
- coding standard (dumb)
- static analysis (not-so-dumb)

Please consider adding https://github.com/JakubOnderka/PHP-Parallel-Lint

**Comment by dingo-d** [comment]
We had this in earlier versions, but abandoned this in favour of PHPCS. Also, we use PHP native linter in the [lintPHP.sh](https://github.com/infinum/wp-boilerplate/blob/development/bin/lintPhp.sh) that is ran on the commit action if I'm not mistaken.

I will probably look into implementing PHPStan, as the results of that scan look really interesting :+1:

**Comment by szepeviktor** [comment]
> we use PHP native linter in the [lintPHP.sh](https://github.com/infinum/wp-boilerplate/blob/development/bin/lintPhp.sh) [](/infinum/wp-boilerplate/blob/HEAD@{2019-08-29T10:59:43Z}/bin/lintPhp.sh)

That shell script is not something you are looking for, please reconsider the above PHP pkg.

**Comment by szepeviktor** [comment]
> I will probably look into implementing PHPStan, as the results of that scan look really interesting 👍
