### ISSUE TITLE
Problem with WPML.... css/js 404 not found

### ISSUE THREAD

**Issue by PatriceBois** [infinum/wp-boilerplate#166]
Is there any thing we have to do to make it work with WPML.

The native language is working but when we are switching to another, we got 404 error for the css/js etc..
![Capture d’écran 2019-09-18 à 19 37 53](https://user-images.githubusercontent.com/4474398/65195129-ea4fa000-da4b-11e9-9283-acecb54b57ec.png)

**Comment by IvanGrginovInf** [comment]
Hi @PatriceBois, we haven't had those issues with Polylang or WPML but we'll investigate.

Meanwhile you should be able to fix it with a wildcard redirect using something like (you need regex support) https://wordpress.org/plugins/redirection/

The redirect code **should** be this one (you will have to test it yourself):

- From: `http://emswdev.com/provalis/*/wp-content/themes/provalis/skin/public/(.*)`
- To: `http://emswdev.com/provalis/wp-content/themes/provalis/skin/public/$1`

**Comment by iruzevic** [comment]
Hi Patrice,

could you please give us the manifest.json data and if you could give use what version of the boilerplate are you using?

The problem here is that WPML adds language to the url. Manifest outputs the relative assets path, that means that the url will be wrong. Please output your manifest.json here and boilerplate version and I will provide you with the fix

**Comment by PatriceBois** [comment]
Where can i found the manifest.json, i can't seem to find it

=== Eightshift WordPress Boilerplate ===
Contributors: mustra, dingo_d, ivangrginov
Tags: custom-menu, editor-style, featured-images, one-column, theme-options	, translation-ready
Requires at least: 4.4
Requires PHP: 7.0
Tested up to: 5.1.1
Stable tag: 1.0.0
License: MIT
License URI: https://opensource.org/licenses/MIT

**Comment by PatriceBois** [comment]
"version": "4.0.0",
  "author": "Team Eightshift",
  "main": "",

**Comment by iruzevic** [comment]
menifest.json can be found in theme/skin/public/manifest.json

**Comment by PatriceBois** [comment]
{
  "application.css": "wp-content/themes/provalis/skin/public/application-c937192740bedc818b8e.css",
  "application.js": "wp-content/themes/provalis/skin/public/application.js",
  "applicationAdmin.css": "wp-content/themes/provalis/skin/public/applicationAdmin-c937192740bedc818b8e.css",
  "applicationAdmin.js": "wp-content/themes/provalis/skin/public/applicationAdmin.js",
  "jquery.min.js": "wp-content/themes/provalis/skin/public/jquery.min.js",
  "logo.svg": "wp-content/themes/provalis/skin/public/logo.svg"
}

**Comment by PatriceBois** [comment]
Any updates? Thanks

**Comment by emisrw** [comment]
+1 The same problem with polylang.
$this->manifest->get_assets_manifest_item( 'application.css' ) 
Returns path with language. 
For example mydomain.com/en/wp-content/themes/.... instead  mydomain.com/wp-content/

**Comment by iruzevic** [comment]
Hi sorry for the long delay.

I will fix this in the next release but you can fix it with this.
In your theme go to src>manifest>class-manifest.php
and add this code inside:

```php
 /**
   * Retrun string as an assets output prefix.
   * Override this if you are using lib for a plugin.
   *
   * @return string
   */
  protected function get_assets_manifest_output_prefix() : string {
    return site_url( '/' );
  }
```

by default i have put home_url instead of site_url
