### ISSUE TITLE
Add check to see if ACF is installed

### ISSUE THREAD

**Issue by dingo-d** [infinum/wp-boilerplate#2]
On page templates and places where ACF functions are used we should do a check to see if ACF is installed with 

`if ( class_exists( 'acf' ) )`

This will make the boilerplate work even without it installed.

As a side idea, when we'll fiddle with automation, we could make a pre checks to see which plugin will be installed (acf, woocommerce etc.), and include certain files according to that.

**Comment by iruzevic** [comment]
I have added function_exists check, recommendation is to use that
