### ISSUE TITLE
Fix footer get_template_part() inside footer.php

### ISSUE THREAD

**Issue by dingo-d** [infinum/wp-boilerplate#26]
Inside `footer.php` there is

https://github.com/infinum/wp-boilerplate/blob/aa753dccb1d3260fc4e1b20fadb1485b94b9fb27/wp-content/themes/theme_name/footer.php#L12-L14

Which should be

```php
<?php
get_template_part( 'template-parts/footer/footer', 'content' );

get_template_part( 'template-parts/footer/foot' );

```

**Comment by iruzevic** [comment]
fixed
