### ISSUE TITLE
Fix for windows when running "npm run build" and  problem with "npm run precommit"

### ISSUE THREAD

**Issue by marko-mlinarevic** [infinum/wp-boilerplate#29]
When trying to use boilerplate on windows build script  needs to be changed

npm run build

in package.json change to this

```
"build": "SET NODE_ENV=production & webpack --progress"
```

and for precommit,  the problem is in stylelint config file rules

```
"selector-no-id": true,
"selector-no-type": true,
"selector-no-universal": true,
```

are deprecated since 8.0.0 version and need to removed

**Comment by iruzevic** [comment]
Hy tnx for the comment on build, we at Infinum are all using macs so I will not change the package.json. If there are more Win users they will have this ticket to refer to.

Regarding the stylelint yes they did deprecated but they didn't removed it just changed the names so we did the corrections:
`
-    "selector-no-id": true,
-    "selector-no-type": true,
-    "selector-no-universal": true,
+    "selector-max-id": 0,
+    "selector-max-type": 4,
+    "selector-max-universal": 0,
`
