### ISSUE TITLE
cannot find fonts while compiling 

### ISSUE THREAD

**Issue by marko-mlinarevic** [infinum/wp-boilerplate#32]
When I try npm run build i get this error

```
[D:\data\xampp\htdocs\wpwp2\wp-content\themes\wpwp2\skin\assets\styles\..onts\icomoon.woff]
[D:\data\xampp\htdocs\wpwp2\wp-content\themes\wpwp2\skin\assets\styles\..onts\icomoon.woff.js]
[D:\data\xampp\htdocs\wpwp2\wp-content\themes\wpwp2\skin\assets\styles\..onts\icomoon.woff.json]
[D:\data\xampp\htdocs\wpwp2\wp-content\themes\wpwp2\skin\assets\styles\..onts\icomoon.woff]

```

Do you have any idea what it could be(there are fonts in fonts folder)?

EDIT: I found a work around for now I simply changed the name of the fonts folder and now it works.

**Comment by dingo-d** [comment]
Icon font should be located in `theme_name\skin\assets\fonts`, also be sure to add `.woff`, `.eot`, `.ttf`, `.svg` and `selection.json`. And be sure that you changed the theme name in the `postcss.config.js` file.

**Comment by marko-mlinarevic** [comment]
I did all that but i still get this error. It's like it's looking into a wrong folder

```
Error: Can't resolve './..onts/icomoon.woff' in 'D:\data\xampp\htdocs\wpwp2\wp-content\themes\wpwp2\skin\assets\styles'
        resolve './..onts/icomoon.woff' in 'D:\data\xampp\htdocs\wpwp2\wp-content\themes\wpwp2\skin\assets\styles'
          using description file: D:\data\xampp\htdocs\wpwp2\package.json (relative path: ./wp-content/themes/wpwp2/skin/assets/styles)

```

**Comment by dingo-d** [comment]
Try to check if there is some hidden character in your `package.json` file (usualy character that you cannot distinguish from space), or dangling comma. You can also post your `package.json` file here so that we can compare it.

**Comment by marko-mlinarevic** [comment]
```
{
  "name": "wpwp2",
  "version": "1.0.0",
  "private": true,
  "main": "postcss.config.js",
  "scripts": {
    "__sassUnusedTheme": "sass-unused \"wp-content/themes/wpwp2/**/*.scss\"",
    "__eslintTheme": "eslint wp-content/themes/wpwp2/skin/assets/",
    "__stylelintTheme": "stylelint \"wp-content/themes/wpwp2/**/*.scss\" --syntax scss",
    "precommit": "npm run __eslintTheme && npm run __stylelintTheme && npm run __sassUnusedTheme",
    "start": "webpack --progress --watch --display-error-details --display-modules --display-reasons",
    "build": "SET NODE_ENV=production && webpack --progress"
  },
  "devDependencies": {
    "autoprefixer": "^7.1.3",
    "babel-core": "^6.26.0",
    "babel-eslint": "^7.2.3",
    "babel-loader": "^7.1.2",
    "babel-preset-env": "^1.6.0",
    "browser-sync": "^2.18.13",
    "browser-sync-webpack-plugin": "^1.2.0",
    "clean-webpack-plugin": "^0.1.16",
    "copy-webpack-plugin": "^4.0.1",
    "css-loader": "^0.28.5",
    "css-mqpacker": "^6.0.1",
    "cssnano": "^3.10.0",
    "eslint": "^4.5.0",
    "extract-text-webpack-plugin": "^3.0.0",
    "file-loader": "^0.11.2",
    "node-sass": "^4.5.3",
    "postcss-cssnext": "^3.0.2",
    "postcss-font-magician": "^2.0.0",
    "postcss-loader": "^2.0.6",
    "precss": "^2.0.0",
    "sass-loader": "^6.0.6",
    "sass-unused": "^0.2.2",
    "style-loader": "^0.18.2",
    "stylelint": "^8.0.0",
    "uglifyjs-webpack-plugin": "^0.4.6",
    "webpack": "^3.5.5",
    "webpack-bundle-analyzer": "^2.9.0",
    "webpack-modernizr-loader": "^4.0.0"
  },
  "dependencies": {
    "caniuse-lite": "^1.0.30000733",
    "jquery": "^3.2.1",
    "jquery-match-height": "^0.7.2",
    "lodash": "^4.17.4",
    "magnific-popup": "^1.1.0",
    "media-blender": "^2.1.0",
    "normalize.css": "^7.0.0",
    "slick-carousel": "^1.7.1",
    "strman": "^2.0.0",
    "susy": "^3.0.1"
  },
  "browserslist": [
    "android >= 4.2",
    "not ie < 11",
    "last 2 versions"
  ],
  "description": "This repo is used to start with your WordPress project.",
  "license": "ISC"
}
```

**Comment by dingo-d** [comment]
Why do you have `"main": "postcss.config.js",` ? Try emptying it `"main": "",`

**Comment by marko-mlinarevic** [comment]
it was there when I downloaded for the first time from github. I tried but it didn't work. I get the same error

**Comment by dingo-d** [comment]
Do you have a repo with this so that we can inspect the code? It could be a lot of things, plus windows is totally different than mac as a dev environment.

**Comment by marko-mlinarevic** [comment]
I will put code tonight to my github page

**Comment by marko-mlinarevic** [comment]
https://github.com/marko-mlinarevic/wp-testing-boilerplate

here it is

**Comment by dingo-d** [comment]
Ok so there are few things that I noticed. I had the error while starting the webpack with `CopyWebpackPlugin`, the `pathTheme` variable wasn't defined, so I just commented it out.

Then you changed the fonts folder to `efonts` for some reason, but ok. In the that folder in the `efonts.js` you don't actually need to include icon font, postcss picks it up. The issue is that the font name is `ìcomoon`, and the font name specified in the `_placeholders.scss` is `north2`. Once I changed that to `icomoon`, icons worked fine in the theme.

So change the icons name in the `_placeholders.scss` so that they match the loaded icon font in the fonts assets folder.

We have a plan to make more detailed step by step documentation on how to change some settings, add fonts, images etc.

**Comment by marko-mlinarevic** [comment]
Ok I did what you did, and by method of elimination i figured out why it won't compile. in postcss.config.js

if 
```
const fontsPath = path.join(__dirname, `wp-content/themes/${themeName}/skin/assets/fonts`);
```

have a same name as folder name in assets it doesn't work it throws out for each font this error
```
ERROR in ./node_modules/css-loader!./node_modules/postcss-loader/lib!./node_modules/sass-loader/lib/loader.js!./wp-content/themes/wpwp2/skin/assets/styles/application.scss
        Module not found: Error: Can't resolve './..onts/icomoon.woff' 
```
But why does in command line says 
```
\..onts\
```
these two dots are suspicious to me

**Comment by dingo-d** [comment]
Oh, and did you change this folder in your `postcss.config.js` to `efonts`? Because it's set to `efonts` on your git.

**Comment by marko-mlinarevic** [comment]
sry didn't commit changes. yes that was changed. For example if you have folder in your assets that's called efonts and in postcss.config.file you have the same name(so you are pointing to folder that exist). It will throw out an error.

**Comment by dingo-d** [comment]
What error? When you make any changes either to the postcss or webpack you need to rerun the `npm start` command. I fixed the issues that I described above and your theme compiled fine and the icons were showing.

I can provide the changed files if you like.

**Comment by marko-mlinarevic** [comment]
Sry for not responding sooner thanks for the help
