### ISSUE TITLE
Create node based setup and rename scripts?

### ISSUE THREAD

**Issue by dingo-d** [infinum/wp-boilerplate#43]
Windows users could have issues with running bash scripts. Node is required for the boilerplate to run anyhow, so we could try to rewrite using node scripts?

There are powerful [file system](https://nodejs.org/api/fs.html) methods in node, and regexes for matching are basically the same, so this could be done from when `npm install` is run.

**Comment by iruzevic** [comment]
this is done and only needs some more testing but it will be on master in version 3.0.0
