### ISSUE TITLE
Removing empty index.php files

### ISSUE THREAD

**Issue by dingo-d** [infinum/wp-boilerplate#49]
We should probably not encourage 'security through obscurity' mindset, by having empty `index.php` files thrown around the theme. In the end, it's up to the site owner to allow or forbid directory browsing.

Some references:

https://wordpress.stackexchange.com/a/167998/58895

https://wordpress.stackexchange.com/a/45366/58895

**Comment by iruzevic** [comment]
I agree about this but as the comment says: "This file is just there if the server (Apache, Nginx, Lighttp, etc.) is not properly set up "

This boilerplate for the general population and unfortunately a lot of them don't know how to setup correctly everything so if this can help I would like to keep it.

**Comment by dingo-d** [comment]
Ok, we'll put in the documentation that this should be avoided, but we left it for legacy reasons.
