### ISSUE TITLE
Advancing the PHP code a bit

### ISSUE THREAD

**Issue by dingo-d** [infinum/wp-boilerplate#56]
Since we are writing in PHP, let's start writing the proper PHP, not WordPress PHP. We're already on a really good way with namespaces and autoloading but we can do more. I'll list some things we can try to add:

### Interfaces

[Interfaces](http://php.net/manual/en/language.oop5.interfaces.php) define which methods a class must implement, without defining how they are handled.

We should see if we can implement them in the boilerplate. 

The steps needed to achieve this is:

* Find classes that look like they have same methods, but with small modifications to them

* Write an interface with those methods

* Replace pure classes with ones that implement the newly created interface

We should also investigate a bit how the code is structured in regular PHP projects and try to mimic that, following the naming set by the project structure so that autoloader can do its magic.

### Decorator pattern

Decorators, as described [here](https://phpenthusiast.com/blog/the-decorator-design-pattern-in-php-explained), are used dor adding new optional features to the code without changing the existing classes.

For this, we need interfaces because decorators in php are abstract classes which implement a certain interface (the one that the class you want to extend implements as well).

We should see where (if anywhere) we can use this and implement it.

### Dependency injection

Again we should have interfaces for this, although it's not a prerequisite. Dependency injection means that, whenever we need to use methods from one class in another class, we shouldn't explicitly define it in that class's methods, but make it dependent in their constructor. This is especially important if we have parameters in one class's constructor. Later on if you need to change it, you need to search through all your code to find out where you instantiated that class and change how you call it. A good example of it can be found [here](https://code.tutsplus.com/tutorials/dependency-injection-in-php--net-28146).

```php
class Author {
    private $firstName;
    private $lastName;
 
    public function __construct($firstName, $lastName) {
        $this->firstName = $firstName;
        $this->lastName = $lastName;
    }
 
    public function getFirstName() {
        return $this->firstName;
    }
 
    public function getLastName() {
        return $this->lastName;
    }
}
 
class Question {
    private $author;
    private $question;
    public function __construct($question, $authorFirstName, $authorLastName) {
        $this->author = new Author($authorFirstName, $authorLastName);
        $this->question = $question;
    }
 
    public function getAuthor() {
        return $this->author;
    }
 
    public function getQuestion() {
        return $this->question;
    }
}
```

If you change the `Author` method and say add `$this->age = $age` in the constructor, you'll need to manually change it in the `Question` class when defining `$this->author`.

We could try to see if and how we could use [DI containers](https://codeburst.io/dependency-injection-di-container-in-php-a7e5d309ccc6).

This basically means we would have to see how our classes interact and how to solve this dependency issue.

### Using static methods where needed

As [per definition](http://php.net/manual/en/language.oop5.static.php), declaring class properties or methods as static makes them accessible without needing an instantiation of the class. A property declared as static cannot be accessed with an instantiated class object (though a static method can).

We should investigate if we have such methods or properties. Since there is no need to instantiate a whole class, just to access one method/property.

### Putting the code on packagist

We have coding standards on packagist, no reason not to have this there as well, and use full power of the Composer.

----------

These are some suggestions to consider when going forward with the boilerplate development. Plus we would actually learn how to use the things that the whole PHP community is using for ages.

**Comment by iruzevic** [comment]
All this cool stuff is added in #84 branch and it will be pushed to master on version 3.0.0
