### ISSUE TITLE
Create working bundled theme with each release

### ISSUE THREAD

**Issue by dingo-d** [infinum/wp-boilerplate#74]
With every release we should bundle a working zip of a theme, if users just want to use it manually.

For this #73 PR should be merged, and when we bundle the theme, a `composer.json` should be placed inside the theme with 

```json
"autoload": {
    "classmap": [
      "."
    ]
  }
```

So that the classmap is correctly created.

Also the `functions.php` should change the autoload `require` to

`require __DIR__ . '/vendor/autoload.php';`

The way we use it is meant for CI/CD pipeline usage, but many users are not familiar with it. This will help us with broadening our audience and maybe encourage new developers to try developing the way we described in the readme.

**Comment by iruzevic** [comment]
we will have this in mind on every release.
