### ISSUE TITLE
Webfontloader via npm?

### ISSUE THREAD

**Issue by dingo-d** [infinum/wp-boilerplate#75]
I'm not 100% sure why is the webfont bundled in the vendors. Couldn't this be added using npm?

https://github.com/typekit/webfontloader
https://www.npmjs.com/package/webfontloader

**Comment by iruzevic** [comment]
jep this works via npm will be added to master in version 3.0.0

**Comment by dingo-d** [comment]
Do you have a branch open for this?

**Comment by iruzevic** [comment]
this is in branch #84
