### ISSUE TITLE
Autoload dump is necessary after all

### ISSUE THREAD

**Issue by dingo-d** [infinum/wp-boilerplate#77]
It seems that we should add 

`composer -o dump-autoload`

https://github.com/infinum/wp-boilerplate/blob/b74f0c6af34fa806bcf5a866fc2dd39cc033d86b/_build.sh#L5

In one of the projects I'm working on the composer only created classmaps of the project file, not of the included files from composer, and that caused some errors. So my thinking is, it can't hurt, no?

**Comment by iruzevic** [comment]
this is added in production so we can close this issue

**Comment by dingo-d** [comment]
But it's not in the master branch in the build script 😕

**Comment by iruzevic** [comment]
sorry it is in this branch #84
