### ISSUE TITLE
Usage of filemtime() for enqueue - only during development?

### ISSUE THREAD

**Issue by dingo-d** [infinum/wp-boilerplate#79]
As noted in the comment [here](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/pull/1378#issuecomment-398784410), `filemtime` shouldn't be used in production (function call instead of string).

We should see if we can somehow update this so that we are only using it during development for caching purposes.

**Comment by dingo-d** [comment]
Idea: try to see if webpack can be used to generate `manifest.json` that can be converted to array that can be included and then the version can be read from there - this solves the file read problem that `filemtime`produces.

**Comment by iruzevic** [comment]
I think this can be done. I have created a manifest.json and will test how this works on assets

**Comment by iruzevic** [comment]
this is done and it will be pushed to master in version 3.0.0 you can check it out in  #84  branch
