### ISSUE TITLE
Pass mode parameter in build/dev script?

### ISSUE THREAD

**Issue by dingo-d** [infinum/wp-boilerplate#89]
Currently, the `mode` parameter is set to `development`, and I'm not seeing it being changed in any way when doing a production build.

https://github.com/infinum/wp-boilerplate/blob/10259122f9ebca6e01de17180783ddddc59d29ef/webpack.config.js#L153

We can leave that out and add in the `package.json`

```json
"start": "webpack --progress --watch --display-error-details --display-reasons --mode development",
"build": "NODE_ENV=production webpack --progress --mode production"
```

**Comment by iruzevic** [comment]
Great will be added in #91
