### ISSUE TITLE
Continuous integration scripts

### ISSUE THREAD

**Issue by dingo-d** [infinum/wp-boilerplate#90]
I've talked to our devops and we agreed that we should standardize how we run our continuous deployment.

We will need to add a `CI` folder which will contain `build.sh` script and `deploy.sh` script.

The `build.sh` will contain `phpcs` tests (if needed integration tests for `phpunit`) and will be run on every branch push and `deploy.sh` will run when build script passes (this will contain stuff currently in the `_build.sh` script).

An example would look like

Build:

```bash
composer self-update
composer require phpcs
phpcs set config ....
vendor/bin/phpcs ....
```

Deploy:

```bash
composer install --no-dev --no-scripts
npm install
npm run build
```

In the `.gitignore` (if it's not added), we should add `node_modules/**`(so that every `node_modules` in the subdirectories are excluded) and add in the `ci-exclude.txt` all that is not needed for the deployment (for `rsync`).

We should also see how to standardize the database deployment using `wp-cli` (based on the current import/export scripts).

**Comment by iruzevic** [comment]
this is implemented. Add linting and precommits have a new issue. I will close this
