### ISSUE TITLE
Update build process

### ISSUE THREAD

**Issue by dingo-d** [infinum/wp-boilerplate#93]
Core download should be performed without content `wp core download --skip-content` so that akismet and hello dolly plugins are not loaded.

We should also probably add prompts to add necessary info when installing the core so that we can setup the `wp-config.php` as well (`wp config create`).

And we need to modify the readme, since to run rename script you first need to install npm.

**Comment by iruzevic** [comment]
i have added wp core download --skip-content

**Comment by iruzevic** [comment]
As we are using Semafor for CI we have build and deploy.

All scripts should be inside the bin folder in the root of the project.

Build script should install necessary stuff  like npm, composer and run tests like phpcs or any other we need dependong on the project.

Deploy should run the same as build but without the tests.

For now I will ad this two scripts in the version 3 but without the tests. We will add the tests later on when we will have more time to test them.

And we should update the readme and handbook.

Agreed?

**Comment by iruzevic** [comment]
i have also added additional setup stuff

**Comment by dingo-d** [comment]
LGTM :+1:
