### ISSUE TITLE
unsupported.js not found

### ISSUE THREAD

**Issue by shaunmac** [infinum/wp-boilerplate#94]
## Current Behavior

After running `npm run rename` I get an error:

```
module.js:559
    throw err;
    ^

Error: Cannot find module '../lib/utils/unsupported.js'
    at Function.Module._resolveFilename (module.js:557:15)
    at Function.Module._load (module.js:484:25)
    at Module.require (module.js:606:17)
    at require (internal/module.js:11:18)
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:19:21
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:145:3)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)

```

## Expected Behavior

A cli installer runs to rename files for development.

## Possible Solution

The file it's looking for doesn't exist, nor dose the directories its looking in:
`../lib/utils/unsupported.js'`

Should this file and folders  be in the repo? or am I missing something in the readme?

## Steps to Reproduce (for bugs)

1. Installed WP on MAMP 
2. Downloaded wp-boilerplate 
3. Put all files in wp-boilerplate into new wp install
4. In terminal in wp install folder `npm run rename`

## Your Environment

* PHP version: 7.10
* Development environment: MAMP
* Server type: Apache
* Operating System and version: OSX

**Comment by dingo-d** [comment]
What node and npm version do you have on your mamp?

**Comment by shaunmac** [comment]
I'm trying to "re" install node now.
I think it's a node problem more than this repo's. I'll close the issue. 
Sorry for the inconvenience.

**Comment by dingo-d** [comment]
No problem, if you find any bug or something just ask 😄
